################ English language ##################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/en"
weight = 2

[zh]
languageName = "Zh"
languageCode = "en-us"
contentDir = "content/zh"
weight = 1

