############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "Notes"
url = "/notes"
weight = 3

# [[main]]
# name = "Works"
# url = "/works"
# weight = 4

[[main]]
name = "Codes"
url = "/codes"
weight = 4





# footer menu
# [[footer]]
# name = "About"
# url = "/about"
# weight = 1

# [[footer]]
# name = "Works"
# url = "/works"
# weight = 2

# [[footer]]
# name = "Privacy Policy"
# url = "/privacy-policy"
# weight = 2
